### ISSUE TITLE
comm 게시판 글이 삭제가 안됩니다

### ISSUE THREAD

**Issue by llet1942** [Amanokaze/awsdjango-books#4]
```
def board_comm_list_page(request, category):
	error_flag = False

   if request.method == "POST" and request.POST['title']
```
라고 바꾸면 MultiValueDictKeyError 가 발생해서 POST.get('title','') 으로 바꿧더니 에러는 발생하지 않지만 글이 삭제가 안됩니다.

**Comment by gpsuser11** [comment]
https://amanokaze.github.io/blog/Wrong-Words-Modification/ 
dusqus 에 인증이 안되서 아이디 등록이 안되서 여기다가 남깁니다. 

위에 에러는 
board_comm_view.html 에서 id="delete_form" 이 빠져 있어서  views.py에서 
board_delete_result() 를 호출해야하는데  board_comm_list_page() 를 호출하면서 발생한 에러입니다. 
위에 게시판에도 에러가 있다고 되어 있는데, 확인을 안한 것 같네요. 

	<form action="{% url 'boarddeleteres' %}" **id="delete_form"** method="POST" data-id="{{ object.id }}">
					<input type="hidden" name="article_id" value="{{ object.id }}" />
					<input type="hidden" name="referer" value="comm" />
					{% csrf_token %}
					<p>
					<span style="cursor:pointer" onClick="modifyClick({{ object.id }})">수정</span>
					<span style="cursor:pointer" onClick="deleteClick({{ object.id }})">삭제</span>
					</p>
					</form>

**Comment by Amanokaze** [comment]
> https://amanokaze.github.io/blog/Wrong-Words-Modification/
> dusqus 에 인증이 안되서 아이디 등록이 안되서 여기다가 남깁니다.
> 
> 위에 에러는
> board_comm_view.html 에서 id="delete_form" 이 빠져 있어서 views.py에서
> board_delete_result() 를 호출해야하는데 board_comm_list_page() 를 호출하면서 발생한 에러입니다.
> 위에 게시판에도 에러가 있다고 되어 있는데, 확인을 안한 것 같네요.
> 
> ```
> <form action="{% url 'boarddeleteres' %}" id="delete_form" method="POST" data-id="{{ object.id }}">
> 				<input type="hidden" name="article_id" value="{{ object.id }}" />
> 				<input type="hidden" name="referer" value="comm" />
> 				{% csrf_token %}
> 				<p>
> 				<span style="cursor:pointer" onClick="modifyClick({{ object.id }})">수정</span>
> 				<span style="cursor:pointer" onClick="deleteClick({{ object.id }})">삭제</span>
> 				</p>
> 				</form>
> ```

안녕하세요 그동안 관리를 쭉 못해와서 확인이 늦었던 점 양해 바라겠습니다.
해당 사항에 대해서는 누락된 점 양해를 바라며 수정 진행토록 하겠습니다. 
좀 더 주의토록 하겠습니다.

**Comment by Amanokaze** [comment]
Pull Request
